import Link from 'next/link'
import './globals.css'
import styles from './layout.module.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <title>연습</title>
      </head>
      <body> 
        <header className={styles.header}> {/*임포트한 css 모듈 styles파일 안에 있는 .header 선택자를 사용*/}
          <Link href="/">Demo Note</Link>
          <nav className={styles.nav}> {/*임포트한 css 모듈 styles파일 안에 있는 .nav 선택자를 사용*/}
            <Link href='/products'>Products</Link>
            <Link href='/about'>About</Link>
            <Link href='/contact'>Contact</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
